/**
 * Announcement Service
 * Loads the latest announcement manifest snapshot (generated by
 * scripts/announcement/generate-manifest.mjs) so the broadcast path always
 * uses fresh, catalog-derived stats.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const defaultManifestPath = path.resolve(__dirname, '..', 'data', 'announcementManifest.json');

let cached = null;

/**
 * Returns the announcement manifest (memoized). Falls back to a minimal,
 * still-truthful default when the snapshot file hasn't been generated.
 */
export function getAnnouncementManifest() {
    if (cached) return cached;

    try {
        if (fs.existsSync(defaultManifestPath)) {
            cached = JSON.parse(fs.readFileSync(defaultManifestPath, 'utf8'));
            return cached;
        }
    } catch (error) {
        console.error('[Announcement] Failed to read manifest, using defaults:', error.message);
    }

    cached = {
        generatedAt: new Date().toISOString(),
        asOf: new Date().toISOString().slice(0, 10),
        totalComponents: 127,
        latestDropDate: new Date().toISOString().slice(0, 10),
        latestDropCount: 4,
        latestDropByCategory: { 'interactive-background': 3, background: 1 },
        thirtyDayCount: 73,
        featured: [],
        bannerIds: [],
        bannerImage: '/assets/component-previews/announcement-banner.gif',
    };
    return cached;
}